export const IMAGES = {
  LOAD: 'IMAGES_LOAD',
  SUCCESS: 'IMAGES_SUCCESS',
  FAIL: 'IMAGES_FAIL'
}

export const IMG_DATA = {
  LOAD: 'IMG_DATA_LOAD',
  SUCCESS: 'IMG_DATA_SUCCESS',
  FAIL: 'IMG_DATA_FAIL'
}

export const CALORIES = {
  LOAD: 'CALORIES_LOAD',
  SUCCESS: 'CALORIES_LOAD_SUCCESS',
  FAIL: 'CALORIES_LOAD_FAIL',
  ADD: 'CALORIES_ADD_DATA'
}